apiVersion: v1
kind: Namespace
metadata:
  name: dns-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as
  namespace: dns-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
        - name: as
          image: dmx9947/as:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53533
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: as
  namespace: dns-lab
spec:
  type: NodePort
  selector:
    app: as
  ports:
    - name: as-udp
      protocol: UDP
      port: 53533
      targetPort: 53533
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs
  namespace: dns-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
        - name: fs
          image: dmx9947/fs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fs
  namespace: dns-lab
spec:
  type: NodePort
  selector:
    app: fs
  ports:
    - name: fs-tcp
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us
  namespace: dns-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
        - name: us
          image: dmx9947/us:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: us
  namespace: dns-lab
spec:
  type: NodePort
  selector:
    app: us
  ports:
    - name: us-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003